gitmostwanted/blueprints/repo_trending.py
from flask import Blueprint, g, request, render_template

from gitmostwanted.app import db
from gitmostwanted.models import report
from gitmostwanted.models.repo import Repo
from gitmostwanted.models.user import UserAttitude

repo_trending = Blueprint('repo_trending', __name__)


@repo_trending.route('/trending/', defaults={'rng': 'week'})
@repo_trending.route('/trending/<rng>/')
def list_by_range(rng):
    map_list = {'week': 'ReportAllWeekly', 'month': 'ReportAllMonthly'}
    model = getattr(report, map_list.get(rng, map_list.get('week')))

    query = Repo.filter_by_args(model.query, request.args)\
        .join(Repo)\
        .order_by(model.cnt_watch.desc())

    if not g.user:
        query = query.add_columns(db.null())
    else:
        query = UserAttitude.join_by_user_and_repo(query, g.user.id, Repo.id)\
            .with_entities(model, UserAttitude.attitude)

    return render_template('index.html', entries=query, languages=Repo.language_distinct(), rng=rng)

gitmostwanted/blueprints/user_attitude.py
from flask import abort, Blueprint, g, jsonify, render_template, request
from gitmostwanted.models.user import UserAttitude
from gitmostwanted.models.repo import Repo
from gitmostwanted.app import db

user_attitude = Blueprint('user_attitude', __name__)


def verify_attitude(attitude):
    return attitude in ['like', 'dislike', 'neutral']


@user_attitude.before_request
def verify_user():
    if not g.user:
        return abort(403)


@user_attitude.route('/attitude/<int:repo_id>/<attitude>')
def change(repo_id, attitude):
    if not verify_attitude(attitude):
        return abort(403)

    if not Repo.query.get(repo_id):
        return abort(404)

    db.session.merge(UserAttitude(user_id=g.user.id, repo_id=repo_id, attitude=attitude))
    db.session.commit()

    return jsonify(attitude=attitude)


@user_attitude.route('/unchecked/', defaults={'page': 1})
@user_attitude.route('/unchecked/<int:page>')
def list_unchecked(page):
    return list_by_attitude(None, page)


@user_attitude.route('/attitude/<attitude>', defaults={'page': 1})
@user_attitude.route('/attitude/<attitude>/<int:page>')
def list_attitude(attitude, page):
    if not verify_attitude(attitude):
        return abort(403)
    return list_by_attitude(attitude, page)


def list_by_attitude(attitude, page):
    q = UserAttitude.join_by_user_and_repo(Repo.query, g.user.id, Repo.id)\
        .add_columns(UserAttitude.attitude if attitude else db.null())\
        .filter(UserAttitude.attitude == attitude) \
        .order_by(Repo.worth.desc())\
        .order_by(Repo.stargazers_count.desc())

    q = Repo.filter_by_args(q, request.args)

    entries = q.paginate(page=page if page > 0 else 1, per_page=20, error_out=False)
    if entries.pages and entries.pages < entries.page:
        return list_by_attitude(attitude, entries.pages)

    return render_template(
        'repository/attitude.html', repos=entries, attitude=attitude,
        languages=Repo.language_distinct()
    )

gitmostwanted/blueprints/user_oauth.py
from flask import Blueprint, g, redirect, request, session, url_for

from gitmostwanted.app import app, db
from gitmostwanted.models.user import User
from gitmostwanted.services import oauth as service_oauth

user_oauth = Blueprint('user_oauth', __name__)

oauth = service_oauth.instance(app)
oauth.register(
    'github', **app.config['GITHUB_OAUTH'],
    fetch_token=lambda: session.get('oauth_access_token')
)


# @todo #1:15min move before_request method to a general place or a middleware
@app.before_request
def load_user_from_session():
    if str(request.url_rule) in ['/logout']:
        return None
    g.user = User.query.get(session['user_id']) if 'user_id' in session else None


# @todo #2:15min move after_request method to a general place or a middleware
@app.after_request
def browser_cache_flush(response):
    response.headers['X-UA-Compatible'] = 'IE=Edge,chrome=1'
    response.headers['Cache-Control'] = 'no-cache'
    return response


@user_oauth.route('/logout')
def logout():
    session.pop('oauth_access_token', None)
    session.pop('user_id', None)
    return redirect('/')


@user_oauth.route('/oauth/login')
def login():
    return oauth.github.authorize_redirect(
        redirect_uri=url_for('user_oauth.authorized', next=url_next(), _external=True),
        scope=request.args.get('scope')
    )


@user_oauth.route('/oauth/authorized')
def authorized():
    next_url = url_next() or url_for('repo_rating.top')

    resp = oauth.github.authorize_access_token()
    if resp is None or 'access_token' not in resp:
        return redirect(next_url)

    session.permanent = True
    session['oauth_access_token'] = (resp['access_token'], resp['scope'].split(','))

    result = oauth.github.get('user')
    if result:
        json = result.json()
        user = user_get_or_create(json['id'], json['email'], json['login'])
        session['user_id'] = user.id

    return redirect(next_url)


def user_get_or_create(uid: int, user_email: str, user_name: str):
    entity = User.query.filter_by(github_id=uid).first()
    if not entity:
        entity = User(github_id=uid, username=user_name, email=user_email or None)
        db.session.add(entity)
        db.session.commit()
    return entity


def url_next():
    return request.args.get('next') or request.referrer or None

gitmostwanted/blueprints/user_profile.py
import flask
from gitmostwanted.app import db
from gitmostwanted.tasks.github import repo_starred_star
from gitmostwanted.models.user import User, UserAttitude
from gitmostwanted.models.repo import Repo

user_profile = flask.Blueprint('user_profile', __name__)


@user_profile.route('/<name>')
def overview(name):
    entity = User.query.filter_by(username=name).first_or_404()
    repos = Repo.query.join(UserAttitude)\
        .filter(UserAttitude.user_id == entity.id)\
        .filter(UserAttitude.attitude == 'like')\
        .order_by(Repo.language.desc())
    return flask.render_template('profile.html', account=entity, repos=repos)


@user_profile.route('/profile/github/sync')
def github_sync():
    if not flask.g.user:
        return flask.abort(403)

    token, scope = flask.session.get('oauth_access_token')
    if not token:
        return flask.abort(403)

    if 'public_repo' not in scope:
        flask.flash('This action requires additional permissions', 'alert')
    else:
        repo_starred_star.delay(flask.g.user.id, token)
        flask.flash('Synchronisation is successfully queued', 'success')

    return flask.redirect(flask.url_for('user_profile.overview', name=flask.g.user.username))


@user_profile.route('/profile/remove')
def remove():
    if not flask.g.user:
        return flask.abort(403)

    im_sure = flask.request.args.get('im_sure', False)
    if im_sure == 'True':
        db.session.delete(flask.g.user)
        db.session.commit()

    return flask.redirect(flask.url_for('user_oauth.logout'))

gitmostwanted/templates/footer.html
<footer>
  <div class="row" style="margin-top: 19px;">
    <div class="small-offset-3 text-right small-2 columns">
      <a href="https://github.com/kkamkou/gitmostwanted.com/wiki"
         target="_blank" class="label radius primary"><i class="fi-book"></i> WIKI</a>
    </div>
    <div class="small-2 text-center columns">
      <span class="label secondary">{{ config['GITHUB_SHA'] or 'local' }}</span>
    </div>
    <div class="small-5 text-left columns">
      <iframe src="https://ghbtns.com/github-btn.html?user=kkamkou&repo=gitmostwanted.com&type=fork"
              style="margin-top: 4px; border: 0; overflow: hidden; width: 80px; height: 30px;"></iframe>
    </div>
  </div>
</footer>

gitmostwanted/templates/index.html
{% extends "layout.html" %}

{% if rng in ['week', 'month']  %}
  {% set page_title = 'Trending ({})'.format(rng) %}
{% else %}
  {% set page_title = 'Trending' %}
{% endif %}

{% from "macros/attitude.html" import user_attitude %}
{% from "macros/repository.html" import repository, repository_filter %}

{% block body %}
  <ul class="breadcrumbs">
    {% for r in ['week', 'month'] %}
      <li {{ 'class=unavailable' if rng == r }}>
        <a href="{{ url_for('repo_trending.list_by_range', rng=r) }}">{{ r|capitalize() }}</a>
      </li>
    {% endfor %}
    <li><a href="{{ url_for('repo_rating.top') }}">Top&uarr;</a></li>
    {% if g.user %}
      <li><a href="{{ url_for('user_attitude.list_unchecked') }}">Attitude&rarr;</a></li>
    {% else %}
      <li>
        <a href="{{ url_for('user_oauth.login', next=url_for('user_attitude.list_unchecked')) }}">Attitude&rarr;</a>
      </li>
    {% endif %}
  </ul>

  <div class="row" id="gh-entries">
    {% call repository_filter(languages) %}
    {% endcall %}

    <div class="small-12 columns">
      <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
        {% for (entry, attitude) in entries %}
          {% call(repo) repository(entry.repo) %}

            <div class="right">
              <span class="label secondary">
                +{{ entry.cnt_watch|number_humanize }} <i class="fi-star"></i>
              </span>
              {% if repo.mature %}
                <span class="label info">
                  <a href="{{ url_for('repo_information.details', repo_id=repo.id) }}" title="Details"
                    data-reveal-id="repoDetailsModal" data-reveal-ajax="true">
                    {{ repo.stargazers_count|number_humanize }} <i class="fi-graph-bar"></i>
                  </a>
                </span>
              {% endif %}
            </div>

            {% if g.user %}
                {{ user_attitude(repo.id, attitude) }}
            {% endif %}
          {% endcall %}
        {% else %}
          <p class="alert-box secondary">No entries found</p>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div id="repoDetailsModal" class="reveal-modal" data-reveal data-options="animation:false"
    aria-labelledby="repoDetailsModal" aria-hidden="true" role="dialog"></div>
{% endblock %}

gitmostwanted/templates/layout.html
<!DOCTYPE html>
<html>
  <head lang="en">
    <meta charset="UTF-8">

    <title>{{ '%s - ' % page_title if page_title }}GitHub Explore</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Advanced explore of github.com. The main goal is to highlight the most interesting repositories and exclude others.">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/normalize.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/foundation.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>

  <body>
    <div class="wrapper">
      <nav class="top-bar" data-topbar data-options="is_hover: false" role="navigation" style="margin-bottom: 2px">
        <ul class="title-area">
          <li class="name">
            <h1><a href="{{ url_for('repo_rating.top') }}">GitHub Explore</a></h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
        </ul>

        <!-- what is GMW modal -->
        <div id="whatIsGmwModal" class="reveal-modal" data-reveal aria-labelledby="whatIsGmwModalTitle"
          aria-hidden="true" role="dialog">
          <h3 id="whatIsGmwModalTitle">What's It All About?</h3>
          <p>
            Repositories often get hyped when they are created or promoted by big companies. Marketing, events, or other tricks
            can also push some projects into the spotlight. But this doesn’t always mean the repositories are actually useful.<br>
            For example, compare:
            <a href="{{ url_for('repo_rating.top') }}">Top</a> vs
            <a href="https://github.com/search?o=desc&q=stars%3A%3E10000&s=stars&type=Repositories" target="_blank">GitHub search</a>
            ordered by stars.
          </p>
          <p>
            The <strong>gitmostwanted.com</strong> project looks at
            <a href="https://www.githubarchive.org/" target="_blank">githubarchive</a> and highlights the most interesting
            repositories while filtering out the rest. You can read more in the
            <a href="https://github.com/kkamkou/gitmostwanted.com/wiki" target="_blank">Wiki</a>.
          </p>
          <h3>Why login?</h3>
          <p>
            GMW is like your own database where you save <code>liked</code> repositories.
            Once there are 200+ users, it will also suggest people with similar preferences.
            For now, you can sync your GitHub stars and share your public profile link
            (<code>https://gitmostwanted.com/USER_NAME</code>) with friends or teammates. Have fun!
          </p>
          <a class="close-reveal-modal" aria-label="Close">&#215;</a>
        </div>

        <section class="top-bar-section">
          <ul class="right">
            <li>
              <a href="https://github.com/kkamkou/gitmostwanted.com" target="_blank">
                <i class="fi-social-github" title="Fork it!"></i>
                <span class="visible-for-small-only">Fork it!</span>
              </a>
            </li>
            <!--<li><a href="{{ url_for('static_content.sponsorship') }}">Sponsorship</a></li>-->
            {% if not g.user %}
              <li><a href="#" data-reveal-id="whatIsGmwModal">What is it?</a></li>
              <li><a href="{{ url_for('user_oauth.login', scope='user:email') }}">Login via GitHub</a></li>
            {% else %}
              <li class="has-dropdown">
                <a href="#">{{ g.user.username }}</a>
                <ul class="dropdown">
                    <li><a href="{{ url_for('user_profile.overview', name=g.user.username) }}">Profile</a></li>
                    <li><a href="{{ url_for('user_attitude.list_unchecked') }}">Unchecked</a></li>
                    <li><a href="{{ url_for('user_oauth.logout') }}">Log-out</a></li>
                </ul>
              </li>
            {% endif %}
          </ul>
        </section>
      </nav>

      {% block body %}{% endblock %}

      <div class="footer-push"></div>
    </div>

    {% include 'footer.html' %}
  </body>

  {% if not config.DEBUG %}
    <!-- ga -->
    <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-62018427-1', 'auto');
      ga('send', 'pageview');
    </script>
    <!-- /ga -->
  {% endif %}

  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/js/vendor/jquery.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/js/vendor/modernizr.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/js/foundation.min.js"></script>
  <script type="text/javascript" src="//www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='common.js') }}?v=2"></script>
  <script type="text/javascript">
    $(document).foundation();
  </script>

  {% block js %}{% endblock %}
</html>

gitmostwanted/templates/profile.html
{% extends "layout.html" %}

{% set page_title = account.username %}

{% from "macros/messages.html" import flashed_messages %}

{% block body %}
  <ul class="breadcrumbs">
    <li><a href="/">&larr;Trending</a></li>
    <li><a href="{{ url_for('repo_rating.top') }}">Top&uarr;</a></li>
    <li class="unavailable"><a href="#">Profile</a></li>
    <li><a href="{{ url_for('user_attitude.list_unchecked') }}">Attitude&rarr;</a></li>
  </ul>

  {{  flashed_messages() }}

  <div class="row">
    <h2>
      <i class="fi-social-github"></i>
      <a href="https://github.com/{{ account.username }}" target="_blank">{{ account.username }}</a>
    </h2>
    {% if account.id == g.user.id %}
      <ul class="button-group">
        <li>
          <a class="tiny button success"
            href="{{ url_for('user_oauth.login', next=url_for('user_profile.github_sync'), scope='public_repo') }}">
            <i class="fi-loop"></i> Synchronise with GitHub
          </a>
        </li>
        <li>
          <a class="tiny button alert" id="profile-remove"
            href="{{ url_for('user_profile.remove', im_sure=False) }}">
            <i class="fi-trash"></i> Delete account
          </a>
        </li>
      </ul>
    {% endif %}
  </div>

  <div class="row">
    <h3 class="subheader"><i class="fi-star"></i> Liked Repositories</h3>
    {% if repos.count() %}
      <table>
        {% for repo in repos %}
          <tr>
            <td>
              <a href="{{ repo.html_url }}" target="_blank">{{ repo.full_name | truncate(28, True) }}</a>
            </td>
            <td>{{ repo.language or 'N/A' }}</td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p class="alert-box secondary">No entries found</p>
    {% endif %}
  </div>
{% endblock %}

{% block js %}
  <script type="text/javascript">
    $('#profile-remove').click(function () {
      if (!confirm('Are you sure you want to delete your profile? (no way to restore it later)')) {
        return false;
      }
      $(this).attr('href', $(this).attr('href').replace('im_sure=False', 'im_sure=True'));
      return true;
    });
  </script>
{% endblock %}

gitmostwanted/templates/unchecked.html
{% extends "layout.html" %}

{% set pageTitle = 'Unchecked' %}

{% from "macros/navigation.html" import pagination %}
{% from "macros/attitude.html" import user_attitude %}

{% block body %}
  <dl class="sub-nav">
    <dd class="active"><a href="#">Unchecked</a></dd>
    <dd><a href="/">Trending</a></dd>
  </dl>

  <div class="row" id="gh-entries">
    <div class="small-12 columns">
      <ul class="small-block-grid-1 medium-block-grid-1 large-block-grid-3">
        {% for repo in repos.items %}
          <li data-url="{{ repo.html_url }}">
            <div>
              <h4>
                <a href="{{ repo.html_url }}" target="_blank">{{ repo.full_name }}</a>
                {% if repo.language %}
                  <small class="right">{{ repo.language }}</small>
                {% endif %}
              </h4>

              <p>{{ repo.description }}</p>

              {{ user_attitude(repo.id) }}
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>

  {{ pagination(repos, 'user_attitude.unchecked') }}
{% endblock %}