gitmostwanted/blueprints/user_attitude.py
from flask import abort, Blueprint, g, jsonify, render_template, request
from gitmostwanted.models.user import UserAttitude
from gitmostwanted.models.repo import Repo
from gitmostwanted.app import db

user_attitude = Blueprint('user_attitude', __name__)


def verify_attitude(attitude):
    return attitude in ['like', 'dislike', 'neutral']


@user_attitude.before_request
def verify_user():
    if not g.user:
        return abort(403)


@user_attitude.route('/attitude/<int:repo_id>/<attitude>')
def change(repo_id, attitude):
    if not verify_attitude(attitude):
        return abort(403)

    if not Repo.query.get(repo_id):
        return abort(404)

    db.session.merge(UserAttitude(user_id=g.user.id, repo_id=repo_id, attitude=attitude))
    db.session.commit()

    return jsonify(attitude=attitude)


@user_attitude.route('/unchecked/', defaults={'page': 1})
@user_attitude.route('/unchecked/<int:page>')
def list_unchecked(page):
    return list_by_attitude(None, page)


@user_attitude.route('/attitude/<attitude>', defaults={'page': 1})
@user_attitude.route('/attitude/<attitude>/<int:page>')
def list_attitude(attitude, page):
    if not verify_attitude(attitude):
        return abort(403)
    return list_by_attitude(attitude, page)


def list_by_attitude(attitude, page):
    q = UserAttitude.join_by_user_and_repo(Repo.query, g.user.id, Repo.id)\
        .add_columns(UserAttitude.attitude if attitude else db.null())\
        .filter(UserAttitude.attitude == attitude) \
        .order_by(Repo.worth.desc())\
        .order_by(Repo.stargazers_count.desc())

    q = Repo.filter_by_args(q, request.args)

    entries = q.paginate(page=page if page > 0 else 1, per_page=20, error_out=False)
    if entries.pages and entries.pages < entries.page:
        return list_by_attitude(attitude, entries.pages)

    return render_template(
        'repository/attitude.html', repos=entries, attitude=attitude,
        languages=Repo.language_distinct()
    )

gitmostwanted/templates/macros/attitude.html
{% macro user_attitude(repo_id, attitude=None) -%}
  <div class="user-attitude">
    <a href="{{ url_for('user_attitude.change', repo_id=repo_id, attitude='like') }}"
      class="button tiny attitude {{ 'success' if attitude == 'like' else 'secondary' }}"
      data-active-class="success" title="Like it"><i class="fi-like"></i></a>

    <a href="{{ url_for('user_attitude.change', repo_id=repo_id, attitude='neutral') }}"
      class="button tiny attitude {{ 'info' if attitude == 'neutral' else 'secondary' }}"
      data-active-class="info" title="Not sure"><i class="fi-check"></i></a>

    <a href="{{ url_for('user_attitude.change', repo_id=repo_id, attitude='dislike') }}"
      class="button tiny attitude {{ 'alert' if attitude == 'dislike' else 'secondary' }}"
      data-active-class="alert" title="Useless"><i class="fi-dislike"></i></a>
  </div>
{%- endmacro %}

gitmostwanted/templates/macros/messages.html
{% macro flashed_messages(filter=None) -%}
  {% for type, msg in get_flashed_messages(with_categories=True, category_filter=filter) %}
    <div data-alert class="alert-box {{ type }}">
      {{ msg }}
      <a href="#" class="close">&times;</a>
    </div>
  {% endfor %}
{%- endmacro %}

gitmostwanted/templates/macros/navigation.html
{% macro pagination(paginator) -%}

  {% set view_args = request.view_args %}
  {% do view_args.pop('page') %}
  {% do view_args.update(kwargs) %}

  <hr>

  <ul class="button-group text-center">
    {% for page in paginator.iter_pages(left_edge=1, left_current=1, right_current=2, right_edge=1) -%}
      {% if page %}
        {% if page != paginator.page %}
          <li>
            <a href="{{ url_for(request.endpoint, page=page, **view_args) }}"
              class="button tiny secondary">{{ page }}</a>
          </li>
        {% else %}
          <li class="current"><a href="javascript:void(0)"
            class="button tiny disabled">{{ page }}</a></li>
        {% endif %}
      {% else %}
        <li class="unavailable">&nbsp;</li>
      {% endif %}
    {%- endfor %}
  </ul>
{%- endmacro %}

gitmostwanted/templates/macros/repository.html
{% macro repository(repo) -%}
  <li data-url="{{ repo.html_url }}" class="{{ repo.status }}">
    <div>
      <h4>
        <a href="{{ repo.html_url }}" target="_blank">
          {% if repo.worth >= config.REPOSITORY_WORTH_SOLID %}
            <b>{{ repo.full_name }}</b>
          {% else %}
            {{ repo.full_name }}
          {% endif %}
        </a>

        {% if repo.mature %}
          <sup class="secondary label" title="Mature enough (Older than 3 months)">m</sup>
        {% endif %}

        {% if repo.status in ('promising', 'hopeless') %}
          <sup class="{{ 'success' if repo.status == 'promising' else 'warning' }} label"
            title="{{ repo.status|capitalize() }}">{{ repo.status[0] }}</sup>
        {% endif %}

        {% if repo.worth != config.REPOSITORY_WORTH_DEFAULT %}
          {% if repo.worth > config.REPOSITORY_WORTH_DEFAULT %}
            <sup class="secondary label" title="Worth checking out"><i class="fi-lightbulb"></i></sup>
          {% else %}
            <sup class="secondary label" title="Losing popularity"><i class="fi-skull"></i></sup>
          {% endif %}
        {% endif %}

        {% if repo.language %}
          <small class="right">{{ repo.language }}</small>
        {% endif %}
      </h4>

      {% if repo.homepage %}
        <a href="{{ repo.homepage }}" target="_blank">{{ repo.homepage }}</a>
      {% endif %}

      {% if repo.description %}
        <p>{{ repo.description }}</p>
      {% endif %}

      {{ caller(repo) }}
    </div>
  </li>
{%- endmacro %}

{% macro repository_filter(languages) -%}
  <a href="#" data-section="search"
    class="repository-filter button tiny {{ 'success' if request.args.get('term') else 'secondary' }}">
    <i class="fi-magnifying-glass"></i> Search by name
  </a>
  <a href="#" data-section="preset"
    class="repository-filter button tiny {{'success' if (request.args.get('lang', 'All') != 'All' or 'status' in request.args or 'mature' in request.args) else 'secondary' }}">
    <i class="fi-filter"></i> Filter options
  </a>

  <form class="repository-filter">

    {{ caller() }}

    <div class="search hide large-12 columns">
      <div class="row collapse">
        <div class="small-8 medium-10 columns">
          <input type="text" name="term" autofocus="autofocus" maxlength="120"
            value="{{ request.args.get('term', '') }}" placeholder="Search by name">
        </div>
        <div class="small-2 medium-1 columns">
          <a href="#" class="button postfix secondary"
            onclick="$('input[name=term]').val('').trigger('change');return false;"><i class="fi-x"></i></a>
        </div>
        <div class="small-2 medium-1 columns">
          <a href="#" class="button postfix success"><i class="fi-magnifying-glass"></i></a>
        </div>
      </div>
    </div>

    <div class="preset hide">
      <div class="large-12 columns">
        <div class="row collapse">
          <div class="small-10 medium-11 columns">
            <select name="lang">
              <option>All</option>
              {% for (lang,) in languages %}
                <option{{ ' selected="selected"' if request.args.get('lang') == lang }}>{{ lang }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="small-2 medium-1 columns">
            <a href="#" class="button postfix success"><i class="fi-refresh"></i></a>
          </div>
        </div>
      </div>

      <div class="small-12 columns">
        <div class="row">
          <div class="small-2 medium-2 text-right columns">
            <div class="switch small radius">
              <input id="statusPromising" type="radio" value="promising" name="status"
                {{ 'checked' if request.args.get('status') == 'promising' }}>
              <label for="statusPromising"></label>
            </div>
          </div>
          <div class="small-1 columns">
            <span class="label success has-tip" data-tooltip aria-haspopup="true"
              title="Show only Promising repositories">P</span>
          </div>

          <div class="small-2 medium-2 text-right columns">
            <div class="switch small radius">
              <input id="statusHopeless" type="radio" value="hopeless" name="status"
                {{ 'checked' if request.args.get('status') == 'hopeless' }}>
              <label for="statusHopeless"></label>
            </div>
          </div>
          <div class="small-1 columns">
            <span class="label warning has-tip" data-tooltip aria-haspopup="true"
              title="Show only Hopeless repositories">H</span>
          </div>

          <div class="small-2 medium-2 text-right columns">
            <div class="switch small radius">
              <input id="maturityFlag" type="checkbox" name="mature" value="1"
                {{ 'checked' if request.args.get('mature') }}>
              <label for="maturityFlag"></label>
            </div>
          </div>
          <div class="small-1 columns">
            <span class="label secondary has-tip" data-tooltip aria-haspopup="true"
              title="Show only mature enough (older than 3 months) repositories">M</span>
          </div>
          <div class="small-3 columns">&nbsp;</div>
        </div>
      </div>
    </div>
  </form>
{%- endmacro %}