gitmostwanted/blueprints/repo_information.py
from flask import abort, Blueprint, render_template
from gitmostwanted.models.repo import Repo, RepoMean

repo_information = Blueprint('repo_information', __name__)


@repo_information.route('/repository/details/<int:repo_id>')
def details(repo_id):
    repo = Repo.query.get(repo_id)
    if not repo:
        return abort(404)

    means = RepoMean.query.filter(RepoMean.repo_id == repo_id)

    return render_template('repository/details.html', entry=repo, means=means)

gitmostwanted/blueprints/repo_trending.py
from flask import Blueprint, g, request, render_template

from gitmostwanted.app import db
from gitmostwanted.models import report
from gitmostwanted.models.repo import Repo
from gitmostwanted.models.user import UserAttitude

repo_trending = Blueprint('repo_trending', __name__)


@repo_trending.route('/trending/', defaults={'rng': 'week'})
@repo_trending.route('/trending/<rng>/')
def list_by_range(rng):
    map_list = {'week': 'ReportAllWeekly', 'month': 'ReportAllMonthly'}
    model = getattr(report, map_list.get(rng, map_list.get('week')))

    query = Repo.filter_by_args(model.query, request.args)\
        .join(Repo)\
        .order_by(model.cnt_watch.desc())

    if not g.user:
        query = query.add_columns(db.null())
    else:
        query = UserAttitude.join_by_user_and_repo(query, g.user.id, Repo.id)\
            .with_entities(model, UserAttitude.attitude)

    return render_template('index.html', entries=query, languages=Repo.language_distinct(), rng=rng)

gitmostwanted/blueprints/user_attitude.py
from flask import abort, Blueprint, g, jsonify, render_template, request
from gitmostwanted.models.user import UserAttitude
from gitmostwanted.models.repo import Repo
from gitmostwanted.app import db

user_attitude = Blueprint('user_attitude', __name__)


def verify_attitude(attitude):
    return attitude in ['like', 'dislike', 'neutral']


@user_attitude.before_request
def verify_user():
    if not g.user:
        return abort(403)


@user_attitude.route('/attitude/<int:repo_id>/<attitude>')
def change(repo_id, attitude):
    if not verify_attitude(attitude):
        return abort(403)

    if not Repo.query.get(repo_id):
        return abort(404)

    db.session.merge(UserAttitude(user_id=g.user.id, repo_id=repo_id, attitude=attitude))
    db.session.commit()

    return jsonify(attitude=attitude)


@user_attitude.route('/unchecked/', defaults={'page': 1})
@user_attitude.route('/unchecked/<int:page>')
def list_unchecked(page):
    return list_by_attitude(None, page)


@user_attitude.route('/attitude/<attitude>', defaults={'page': 1})
@user_attitude.route('/attitude/<attitude>/<int:page>')
def list_attitude(attitude, page):
    if not verify_attitude(attitude):
        return abort(403)
    return list_by_attitude(attitude, page)


def list_by_attitude(attitude, page):
    q = UserAttitude.join_by_user_and_repo(Repo.query, g.user.id, Repo.id)\
        .add_columns(UserAttitude.attitude if attitude else db.null())\
        .filter(UserAttitude.attitude == attitude) \
        .order_by(Repo.worth.desc())\
        .order_by(Repo.stargazers_count.desc())

    q = Repo.filter_by_args(q, request.args)

    entries = q.paginate(page=page if page > 0 else 1, per_page=20, error_out=False)
    if entries.pages and entries.pages < entries.page:
        return list_by_attitude(attitude, entries.pages)

    return render_template(
        'repository/attitude.html', repos=entries, attitude=attitude,
        languages=Repo.language_distinct()
    )

gitmostwanted/blueprints/user_oauth.py
from flask import Blueprint, g, redirect, request, session, url_for

from gitmostwanted.app import app, db
from gitmostwanted.models.user import User
from gitmostwanted.services import oauth as service_oauth

user_oauth = Blueprint('user_oauth', __name__)

oauth = service_oauth.instance(app)
oauth.register(
    'github', **app.config['GITHUB_OAUTH'],
    fetch_token=lambda: session.get('oauth_access_token')
)


# @todo #1:15min move before_request method to a general place or a middleware
@app.before_request
def load_user_from_session():
    if str(request.url_rule) in ['/logout']:
        return None
    g.user = User.query.get(session['user_id']) if 'user_id' in session else None


# @todo #2:15min move after_request method to a general place or a middleware
@app.after_request
def browser_cache_flush(response):
    response.headers['X-UA-Compatible'] = 'IE=Edge,chrome=1'
    response.headers['Cache-Control'] = 'no-cache'
    return response


@user_oauth.route('/logout')
def logout():
    session.pop('oauth_access_token', None)
    session.pop('user_id', None)
    return redirect('/')


@user_oauth.route('/oauth/login')
def login():
    return oauth.github.authorize_redirect(
        redirect_uri=url_for('user_oauth.authorized', next=url_next(), _external=True),
        scope=request.args.get('scope')
    )


@user_oauth.route('/oauth/authorized')
def authorized():
    next_url = url_next() or url_for('repo_rating.top')

    resp = oauth.github.authorize_access_token()
    if resp is None or 'access_token' not in resp:
        return redirect(next_url)

    session.permanent = True
    session['oauth_access_token'] = (resp['access_token'], resp['scope'].split(','))

    result = oauth.github.get('user')
    if result:
        json = result.json()
        user = user_get_or_create(json['id'], json['email'], json['login'])
        session['user_id'] = user.id

    return redirect(next_url)


def user_get_or_create(uid: int, user_email: str, user_name: str):
    entity = User.query.filter_by(github_id=uid).first()
    if not entity:
        entity = User(github_id=uid, username=user_name, email=user_email or None)
        db.session.add(entity)
        db.session.commit()
    return entity


def url_next():
    return request.args.get('next') or request.referrer or None

gitmostwanted/templates/repository/attitude.html
{% extends "layout.html" %}

{% if attitude in ['like', 'dislike', 'neutral'] %}
  {% set page_title = 'Attitude ({})'.format(attitude) %}
{% else %}
  {% set page_title = 'Attitude' %}
{% endif %}

{% from "macros/attitude.html" import user_attitude %}
{% from "macros/navigation.html" import pagination %}
{% from "macros/repository.html" import repository, repository_filter %}

{% block body %}
  <ul class="breadcrumbs">
    <li><a href="{{ url_for('repo_trending.list_by_range') }}">&larr;Trending</a></li>
    <li {{ 'class=unavailable' if not attitude }}><a
      href="{{ url_for('user_attitude.list_unchecked') }}">New</a></li>
    {% for r in ['like', 'dislike', 'neutral'] %}
      <li {{ 'class=unavailable' if attitude == r }}>
        <a href="{{ url_for('user_attitude.list_attitude', attitude=r) }}">{{ r|capitalize() }}</a>
      </li>
    {% endfor %}
  </ul>

  <div class="row" id="gh-entries">
    {% call repository_filter(languages) %}
    {% endcall %}

    <div class="small-12 columns">
      <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
        {% for (repo, attitude) in repos.items %}
          {% call(repo) repository(repo) %}
            {% if repo.mature %}
              <a href="{{ url_for('repo_information.details', repo_id=repo.id) }}"
                 class="button tiny secondary right" title="Details"
                 data-reveal-id="repoDetailsModal"
                 data-reveal-ajax="true">{{ repo.stargazers_count|number_humanize }}
                <i class="fi-graph-bar"></i></a>
            {% endif %}
            {{ user_attitude(repo.id, attitude) }}
          {% endcall %}
        {% else %}
          <p class="alert-box secondary">No entries found</p>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div id="repoDetailsModal" class="reveal-modal" data-reveal data-options="animation:false"
    aria-labelledby="repoDetailsModal" aria-hidden="true" role="dialog"></div>

  {{
    pagination(
      repos, lang=request.args.get('lang'), status=request.args.get('status'),
      mature=request.args.get('mature'), term=request.args.get('term')
    ) if repos.pages
  }}
{% endblock %}

gitmostwanted/templates/repository/details.html
<h3 id="repoDetailsModalTitle">
  <span onclick="$('#repository-details').toggle()">{{ entry.full_name }}</span>
  <a href="{{ entry.html_url }}" target="_blank"><i class="fi-social-github"></i></a>
</h3>

<div style="margin-bottom: 10px">
  {% if entry.language %}
    <span class="label secondary">{{ entry.language }}</span>
  {% endif %}

  <span class="label secondary" title="Stars">
    {{ entry.stargazers_count|number_humanize }} <i class="fi-graph-bar"></i>
  </span>

  <span class="label secondary" title="Forks">
    {{ entry.forks_count|number_humanize }} <i class="fi-share"></i>
  </span>

  <span class="label secondary" title="Subscribers">
    {{ entry.subscribers_count|number_humanize }} <i class="fi-eye"></i>
  </span>

  {% if entry.license %}
    <span class="label secondary" title="License">
      {{ entry.license }} <i class="fi-shield"></i>
    </span>
  {% endif %}
</div>

<div id="repoDetailsChart" style="min-height: 400px; margin-bottom: 4px;">Generating the popularity chart&hellip;</div>

<div style="margin-bottom: 10px;">
  {% for topic in entry.topics %}
    <span class="label secondary">{{ topic.title }}</span>
  {% endfor %}
</div>

{% if entry.description %}
  <div class="panel">{{ entry.description }}</div>
{% endif %}

<div id="repository-details" class="hide">
  <span class="label secondary" title="Id">{{ entry.id }}</span>
  <span class="label" title="Status">{{ entry.status }}</span>
  <span class="label secondary" title="Worth">{{ entry.worth }}</span>
  {% if entry.status_updated_at %}
    <span class="label secondary" title="Status updated at">{{ entry.status_updated_at.isoformat(timespec='minutes') }}</span>
  {% endif %}
  {% if entry.checked_at %}
    <span class="label secondary" title="Checked at">{{ entry.checked_at.isoformat(timespec='minutes') }}</span>
  {% endif %}
</div>

{% if means %}
  <script type="text/javascript">
      if (!google.charts.Line) {
        google.charts.load('current', {'packages': ['corechart']});
      }

      google.charts.setOnLoadCallback(function () {
        const data = google.visualization.arrayToDataTable([
          ['Date', 'Popularity']
          {% for mean in means %}
            , [new Date("{{ mean.created_at }}"),  {{ '%.1f' | format(mean.value) }}]
          {% endfor %}
        ]);

        setTimeout(function () {
          const holder = $('#repoDetailsChart');
          holder.width(holder.parent().width() + 10)
            .height(~~(holder.parent().height() * 0.6));

          const options = {
            explorer: {
              actions: ['dragToZoom', 'rightClickToReset'],
              axis: 'horizontal',
              keepInBounds: true,
              maxZoomIn: 4,
              maxZoomOut: 1
            },
            axisTitlesPosition: 'in',
            chartArea: {
              top: 10,
              height: holder.height() - 55,
              width: holder.width() > 579 ? holder.width() - 80 : holder.width()
            },
            colors: ['#008CBA'],
            curveType: 'function',
            fontSize: 12,
            hAxis: {gridlines: {color: '#EEE'}, format: 'MMM yy', maxValue: new Date(Date.now() + 1209600000)},
            legend: {position: 'none'},
            lineWidth: 3,
            pointsVisible: false,
            trendlines: {
              0: {color: '#B9B9B9', degree: 2, enableInteractivity: false, tooltip: false, type: 'polynomial'}
            },
            vAxis: {gridlines: {color: '#F3F3F3'}, viewWindowMode: 'maximized'}
          };

          (new google.visualization.DateFormat({pattern: "MMM, yyyy"})).format(data, 0);
          (new google.visualization.ScatterChart(holder.get(0)))
            .draw(data, options);
        }, 200);
      });
  </script>
{% endif %}

<a class="close-reveal-modal" aria-label="Close">&#215;</a>

gitmostwanted/templates/repository/top.html
{% extends "layout.html" %}

{% if sort_by == 'stars' %}
  {% set page_title = 'The most popular repositories' %}
{% elif sort_by == 'wanted' %}
  {% set page_title = 'The most interesting repositories' %}
{% endif %}

{% if filter_worth_by == 'solid' %}
  {% set page_title = '{} ({})'.format(page_title, 'solid') %}
{% elif filter_worth_by == 'rising' %}
  {% set page_title = '{} ({})'.format(page_title, 'rising') %}
{% endif %}

{% from "macros/attitude.html" import user_attitude %}
{% from "macros/navigation.html" import pagination %}
{% from "macros/repository.html" import repository, repository_filter %}

{% block body %}
  <ul class="breadcrumbs">
    <li><a href="{{ url_for('repo_trending.list_by_range') }}">&larr;Trending</a></li>
    <li class="unavailable"><a href="#">Top</a></li>
    {% if g.user %}
      <li><a href="{{ url_for('user_attitude.list_unchecked') }}">Attitude&rarr;</a></li>
    {% else %}
      <li><a href="{{ url_for('user_oauth.login', next=url_for('user_attitude.list_unchecked')) }}">Attitude&rarr;</a></li>
    {% endif %}
  </ul>

  <div class="row" id="gh-entries">
    {% call repository_filter(languages) %}
      <dl class="sub-nav">
        <dd {{ 'class=active' if sort_by == 'wanted' }}><a
          href="{{ url_for('repo_rating.top', sort_by='wanted', page=1, filter_worth_by=filter_worth_by) }}">Wanted</a></dd>
        <dd {{ 'class=active' if sort_by == 'stars' }}><a
          href="{{ url_for('repo_rating.top', sort_by='stars', page=1, filter_worth_by=filter_worth_by) }}">Stars</a></dd>
        <dd><a class="label radius {{ 'info' if filter_worth_by == 'solid' else 'secondary' }}"
          href="{{ url_for('repo_rating.top', sort_by=sort_by, page=1, filter_worth_by='solid') }}">Solid</a></dd>
        <dd><a class="label radius {{ 'info' if filter_worth_by == 'rising' else 'secondary' }}"
          href="{{ url_for('repo_rating.top', sort_by=sort_by, page=1, filter_worth_by='rising') }}">Rising</a></dd>
      </dl>
    {% endcall %}

    <div class="small-12 columns">
      <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
        {% for (repo, attitude) in repos.items %}
          {% call(repo) repository(repo) %}
            <a href="{{ url_for('repo_information.details', repo_id=repo.id) }}"
              class="button tiny secondary right" title="Details"
              data-reveal-id="repoDetailsModal"
              data-reveal-ajax="true">{{ repo.stargazers_count|number_humanize }}
              <i class="fi-graph-bar"></i></a>
            {% if g.user %}
              {{ user_attitude(repo.id, attitude) }}
            {% endif %}
          {% endcall %}
        {% else %}
          <p class="alert-box secondary">No entries found</p>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div id="repoDetailsModal" class="reveal-modal" data-reveal data-options="animation:false"
    aria-labelledby="repoDetailsModal" aria-hidden="true" role="dialog"></div>

  {{
    pagination(
      repos, lang=request.args.get('lang'), status=request.args.get('status'),
      mature=request.args.get('mature'), term=request.args.get('term')
    ) if repos.pages
  }}
{% endblock %}